stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/serveur:$CI_COMMIT_REF_SLUG

cache:
  paths:
    - node_modules/

# Job pour installer les dépendances et construire l'application
build:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/
    expire_in: 1 hour

# Job pour exécuter les tests
test:
  stage: test
  image: node:18-alpine
  script:
    - npm ci
    - npm run test
  dependencies:
    - build

# Job pour construire l'image Docker et la déployer
deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Construire l'image Docker
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

    # Déployer en local avec Docker Compose
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.yml down || true
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
  when: manual
